### ISSUE TITLE
Motions controls not working

### ISSUE THREAD

**Issue by BEERproductions** [v1993/linuxmotehook2#12]
Hi,
I've just started emulating Wii U Games on my Linux system. Since the motion controls don't work on Linux, I'm trying this program. After a while I got cemu to pick up my linuxmotehook controller. But now when I try to play a game like for example Mario Kart 8, the player just randomly moves left to right and doesn't follow the motion of my WiiMote Controller...

https://user-images.githubusercontent.com/67727916/235292611-ede309a0-f8a2-4b38-917b-01937d51f4fc.mp4
In this Video I didn't move the controller at all, except pressing 1 and 2 to go back and forth...
(Yes, the Buttons work)

My Config File:
```
[Linuxmotehook]
Port=26760
Orientation=sideways-left
SendButtons=false
GyroNormalizationFactor=50

[0x001B7AD595F4]
GyroCalibration=235,1395,223
Orientation=sideways-left
SendButtons=true
NunchuckStickCalibration=0,2,95,83
ClassicControllerStickCalibration=0,0,25,25,0,0,25,25
ProControllerStickCalibration=0,0,1000,1000,0,0,1000,1000
```

**My CEMU Config:**
![image](https://user-images.githubusercontent.com/67727916/235292748-62c98085-d651-476e-a9ff-4eb03602085a.png)
![image](https://user-images.githubusercontent.com/67727916/235292761-f42a88ea-a155-41d0-ba1f-9bcf88819233.png)

I have the same problem with multiple controllers.
Did I miss something during setup?

**Comment by v1993** [comment]
Why are you setting values you aren't using? More importantly, why are you setting orientation to `sideways-left`?..

But regardless, Cemu seems to apply some transformation to incoming motion. I can try comping up with an orientation that undoes that, but really, just ask Cemu devs to have an option to turn that off so that motion just maps to wiimote directly. Once that's done, `normal` orientation will work as expected.

I guess you can try using `sideways-right` orientation. I'm not quite sure, but it just might work. Don't hold your breath that it will.

**Comment by BEERproductions** [comment]
Well, thanks for the quick answer. The sideways-right orientation sadly didn't work and my character still randomly jumps around...
